services:
  Lab_1:
    image: lab_1
    build:
      context: .
      dockerfile: Lab1/Dockerfile
    ports:
      - "5123:8080"

  Lab_2:
    image: lab_2
    build:
      context: .
      dockerfile: Lab2/Dockerfile
    ports:
      - "5124:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "Lab3"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5435:5432"