services:
  Lab_1:
    image: lab_1
    build:
      context: .
      dockerfile: Lab1/Dockerfile
    ports:
      - "5123:8080"

  Lab_2:
    image: lab_2
    build:
      context: .
      dockerfile: Lab2/Dockerfile
    ports:
      - "5124:8080"